name: witwat

services:
  # api
  dispatch:
    build:
      context: ./dispatch
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./dispatch:/app
    ports:
      - "8080:8080"
