apiVersion: apps/v1
kind: Deployment
metadata:
  name: dispatch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dispatch
  template:
    metadata:
      labels:
        app: dispatch
    spec:
      containers:
        - name: dispatch
          image: dispatch:dev
          ports:
            - containerPort: 8080
          env:
            - name: RUST_BACKTRACE
              value: "1"
            - name: RUST_ENV
              value: "development"
---
apiVersion: v1
kind: Service
metadata:
  name: dispatch
spec:
  selector:
    app: dispatch
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer
