apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickety-split
  namespace: {{.Values.namespace}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tickety-split
  template:
    metadata:
      labels:
        app: tickety-split
    spec:
      containers:
        - name: tickety-split
          image: {{.Values.frontendImageName}}
          ports:
            - containerPort: 5173
          env:
            - name: VITE_API_URL
              value: {{.Values.apiUrl}}
---
apiVersion: v1
kind: Service
metadata:
  name: tickety-split
  namespace: {{.Values.namespace}}
spec:
  selector:
    app: tickety-split
  ports:
    - port: 5173
      targetPort: 5173
  type: LoadBalancer
