name: "Build and Deploy to GKE"
on:
  push:

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT }}
  GAR_LOCATION: "us-east1"
  GKE_CLUSTER: ${{ secrets.GKE_CLUSTER_NAME }}
  GKE_ZONE: "us-east1-b"

jobs:
  setup-build-publish-deploy:
    name: "Setup, Build, Publish, and Deploy"
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - id: "auth"
        name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WIP_PROVIDER }}
          project_id: ${{ secrets.GCP_PROJECT }}

      - name: Setup gcloud
        uses: "google-github-actions/setup-gcloud@v2"
        with:
          version: ">= 363.0.0"

      - name: Verify Service Account
        run: |
          gcloud auth list
          gcloud config get-value account

      # Authenticate Docker to Google Cloud Artifact Registry
      - name: "Docker Auth"
        uses: "docker/login-action@v3"
        with:
          username: "oauth2accesstoken"
          password: "${{ steps.auth.outputs.auth_token }}"
          registry: "${{ env.GAR_LOCATION }}-docker.pkg.dev"

      # Get the GKE credentials so we can deploy to the cluster
      - name: "Set up GKE credentials"
        uses: "google-github-actions/get-gke-credentials@v2"
        with:
          cluster_name: "${{ env.GKE_CLUSTER }}"
          location: "${{ env.GKE_ZONE }}"
